### ISSUE TITLE
Additional config change needed to Seafile notes (gunicorn.conf)

### ISSUE THREAD

**Issue by pmust** [StarWhiz/docker_deployment_notes#3]
I just tried to use the seafile notes to get my seafile server up and running in docker + caddy setup and noticed that there is a small change that has to be done to the gunicorn.conf file before the server started working (got connection refused error). The thread is here https://forum.seafile.com/t/seafile-and-seahub-start-but-nothing-will-connect-after-upgrade/9204/4 and the change is to modify the default `bind = "127.0.0.1:8000` to `bind = "0.0.0.0:8000`. At least this did the trick for me.

**Comment by StarWhiz** [comment]
Thanks @DemoniWaari I have added that to my documentation.
