### ISSUE TITLE
Initial ubuntu Setup Script needs updating for SSH

### ISSUE THREAD

**Issue by oitconz** [StarWhiz/docker_deployment_notes#5]
Hi.

your initial unbuntu setup script needs an addition for the ssh setup

Unbuntu have now added a permission under /etc/ssh/sshd_config.d/50-cloud-init.conf as PasswordAuthentication yes
It overides the /etc/ssh/sshd_config setting. 

If you add in 
 `sudo sed --in-place 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config.d/50-cloud-init.conf`

It fixes it.

**Comment by StarWhiz** [comment]
Thank you it's been pushed into this commit here https://github.com/StarWhiz/docker_deployment_notes/commit/667c265f17f36983a110444217e2ae23092a113f
